[package]
name = "gol-wasm"
version = "0.0.1"
description = "Package description for gol-wasm"
license = "ISC"

[[module]]
name = "game-of-life"
source = "build/wasi.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name = "gol-wasm"
module = "game-of-life"
runner = "wasi@unstable_"
